version = 1

exclude_patterns = [
  ".github/**",
]

test_patterns = [
  "tests/**",
]

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
