version = 1

exclude_patterns = [
  ".github/**",
  "tests/**",
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "pyproject.toml"
]

  [analyzers.meta]
    max_line_length = 120
    type_checker = "mypy"

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

  [analyzers.meta]
    dialect = "bash"
