language: python
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37

sudo: false

install:
  - pip install coveralls
  - pip install tox

script: tox

after_success: coveralls
