volumes:
  calllogger-data:

services:
  calllogger:
    image: "ghcr.io/quartx-analytics/calllogger:${IMAGE_TAG:-latest}"
    restart: on-failure
    network_mode: host
    volumes:
      - type: volume
        source: calllogger-data
        target: /data
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    group_add:
      - dialout
    environment:
      ENVIRONMENT: "${ENVIRONMENT:-Dockerized}"
