version: "3.9"

volumes:
  calllogger-data:

services:
  calllogger:
    image: "ghcr.io/quartx-analytics/calllogger:latest"
    privileged: true
    restart: on-failure
    network_mode: host
    volumes:
      - type: volume
        source: calllogger-data
        target: /data
      - type: bind
        source: /dev
        target: /dev
    environment:
      DOMAIN: https://quartx.dev/
