name: tests

on:
  push:
    branches: [ rework ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/calllogger
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install test dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir tox

    - name: Test using tox
      run: |
        tox

    - name: Upload test coverage to Codecov
      continue-on-error: true
      uses: codecov/codecov-action@v1
      with:
        flags: unittests

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Set Environment Variables
      run: |
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Build/Push Container Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: Dockerfile
        tags: |
          ${{ env.IMAGE }}:latest
        secrets: |
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Docker Security Scan with Snyk
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.IMAGE }}
        args: --file=Dockerfile

    - name: Upload Security Results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
