name: Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "20 23 */2 * *"
  delete:
    branches-ignore:
      - "main"
      - "dependabot/**"
  pull_request:
    types:
      - closed

env:
  MIN_VERSIONS_TO_KEEP: 10

jobs:
  registry:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    name: Registry Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete all containers from repository without tags
        uses: quartx-analytics/delete-untagged-ghcr-action@new
        with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          except_untagged_multiplatform: true
          untagged_only: true
          owner_type: org

  branch_deleted:
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    name: Branch Deletion
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch Container Image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        continue-on-error: true
        with:
          name: calllogger
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          tag: ${{ github.event.ref }}

  pr-closed:
    if: github.event_name == 'pull_request'
    name: PR Closed
    runs-on: ubuntu-latest
    steps:
      - name: Delete Pull Request Image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          name: calllogger
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          tag: pr-${{github.event.pull_request.number}}
