name: Build Docker Image

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/calllogger" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            ${{ env.IMAGE }}:latest
          build-args: |
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
