name: Build Docker Image

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ghcr.io/quartx/call-logger:latest
          build-args: |
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
