name: mender

jobs:
  mender:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/checkout@v3

      - id: mender
        name: Create mender artifact
        uses: quartx-analytics/mender-docker-compose@main
        with:
          compose-file: compose.yml
          compose-file-variables: IMAGE_TAG=${{ env.IMAGE_TAG }} ENVIRONMENT=Mender
          software-name: calllogger
          software-version: ${{ env.IMAGE_TAG }}
          device-types: raspberrypi3 raspberrypi4
          signing-key: ${{ secrets.ARTIFACT_SIGNING_KEY }}

      - name: Upload mender artifact
        uses: quartx-analytics/mender-artifact-uploader@main
        with:
          artifact: ${{ steps.mender.outputs.artifact-file }}
          username: ${{ secrets.MENDER_USER }}
          password: ${{ secrets.MENDER_PASS }}
