name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          pip install --no-cache-dir tox

      - name: Test using tox
        run: |
          tox

      - name: Upload test coverage to Codecov
        continue-on-error: true
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install test dependencies
        run: |
          python -m pip install flake8

      - name: Test with flake8
        run: |
          flake8 src
